### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nateg921** [rospino74/Quizlet-Bypass#261]
https://quizlet.com/explanations/questions/two-sets-are-called-disjoint-if-they-have-no-elements-in-common-ie-if-their-intersection-is-the-empty-set-prove-that-finite-sets-a-and-b-are-dd0b7e7d-e33b963f-706c-421d-b36b-197681418688

![image](https://user-images.githubusercontent.com/73437724/221364639-5c303f14-33cb-426a-9bcd-86e25ae0c08a.png)

A new account is generated but it doesn't bypass the paywall

**Comment by rospino74** [comment]
As I said in https://github.com/rospino74/Quizlet-Bypass/issues/191#issuecomment-1299157777, only textbook solutions can be unlocked by this extension. Other features, such as questions, cannot be unlocked because Quizlet hard-paywalls them on the backend and does not offer the ability to read them once for free.
