### ISSUE TITLE
Chrome compatibility errors

### ISSUE THREAD

**Issue by SKempiak** [rospino74/Quizlet-Bypass#412]
This extension was working fine for me up until a week or two ago. Now whenever I try to access quizlets paywalled content it just errors out on me. When looking in the extension error menu I am getting two errors:

Unrecognized manifest key 'browser_specific_settings'.

"browser_specific_settings": {
    "gecko": {
      "id": "quizletbypass@rospino74.github.io",
      "strict_min_version": "57.0",
      "update_url": "https://github.com/rospino74/Quizlet-Bypass/raw/master/public/updates.json"
    }
  },
  
  Service worker registration failed. Status code: 2
"background": {
    "service_worker": "serviceWorker.js",
    "type": "module"
  },
  
  Do I need to change anything here? Is it a setting?
<img width="390" alt="Screenshot 2023-09-11 at 1 17 30 PM" src="https://github.com/rospino74/Quizlet-Bypass/assets/28799140/0e44aea0-cb35-4191-bc74-b6e7b82c0308">

**Comment by rospino74** [comment]
Those kinds of problems with service workers seem related to a faulty Chrome installation. Please try updating your browser or installing the extension in a different profile.
If you are on Windows you might also try to install the extension on Edge, just to be sure that the extension file is not corrupted.

BTW, you don't need to worry about the `browser_specific_settings` thing because that's **only** related to **Firefox**.

**Comment by SKempiak** [comment]
Thank you.
